import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FAFC',
  },
  container: {
    padding: 22,
    paddingBottom: 36,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  eyebrow: {
    color: '#177A8A',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  languageButton: {
    minWidth: 52,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#E6F4F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  languageText: {
    color: '#0B5563',
    fontWeight: '900',
  },
  title: {
    color: '#101928',
    fontSize: 36,
    fontWeight: '900',
    lineHeight: 41,
    marginBottom: 10,
  },
  subtitle: {
    color: '#526071',
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 20,
  },
  recorderPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DCE6EE',
    padding: 18,
    alignItems: 'center',
    marginBottom: 16,
  },
  statusRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statusText: {
    color: '#26384D',
    fontSize: 15,
    fontWeight: '800',
  },
  timer: {
    color: '#101928',
    fontSize: 23,
    fontWeight: '900',
  },
  timerUnit: {
    color: '#6A7788',
    fontSize: 13,
    fontWeight: '700',
  },
  waveform: {
    width: '100%',
    height: 112,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
    marginBottom: 18,
  },
  waveSlot: {
    width: 6,
    height: '100%',
    justifyContent: 'center',
  },
  waveBar: {
    minHeight: 8,
    borderRadius: 4,
    backgroundColor: '#00A6D6',
  },
  recordButton: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: '#0E6FFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0E6FFF',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  stopButton: {
    backgroundColor: '#D64545',
    shadowColor: '#D64545',
  },
  recordDot: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
  },
  stopDot: {
    width: 38,
    height: 38,
    borderRadius: 7,
  },
  actionText: {
    color: '#101928',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 14,
  },
  hint: {
    color: '#6A7788',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  resultPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DCE6EE',
    padding: 18,
    marginBottom: 16,
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    color: '#101928',
    fontSize: 16,
    fontWeight: '900',
  },
  estimateBadge: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '900',
  },
  resultLabel: {
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 34,
    marginBottom: 16,
  },
  scoreRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  scoreBlock: {
    flex: 1,
    backgroundColor: '#F3F7FA',
    borderRadius: 8,
    padding: 14,
  },
  scoreLabel: {
    color: '#6A7788',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
  },
  scoreValue: {
    color: '#101928',
    fontSize: 22,
    fontWeight: '900',
  },
  signalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  signalCard: {
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 82,
    backgroundColor: '#F8FBFD',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E1EBF2',
    padding: 10,
    justifyContent: 'center',
  },
  signalLabel: {
    color: '#6A7788',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  signalValue: {
    color: '#101928',
    fontSize: 21,
    fontWeight: '900',
  },
  signalUnit: {
    color: '#6A7788',
    fontSize: 12,
    fontWeight: '800',
  },
  privacyPanel: {
    backgroundColor: '#0F1E2E',
    borderRadius: 8,
    padding: 18,
  },
  privacyTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  privacyBody: {
    color: '#BFD0DF',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 12,
  },
  disclaimer: {
    color: '#D7E5EF',
    fontSize: 12,
    lineHeight: 18,
  },
  privacyLink: {
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingVertical: 6,
  },
  privacyLinkText: {
    color: '#8DE1E8',
    fontSize: 13,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
});
